### ISSUE TITLE
vertical scrolling ?

### ISSUE THREAD

**Issue by ghimireprashant** [PPacie/SwipingCarousel#1]
is it possible to make vertical scrolling?

**Comment by PPacie** [comment]
Sorry, vertical scrolling is not supported. 

You are able to set the scroll direction by overriding `SwipingCarouselFlowLayout prepare()` method. However, I'm afraid it won't have your desired behavior. 

For Example:
```
extension SwipingCarouselFlowLayout {
    override public func prepare() {
        itemSize = CGSize(width: 210.0, height: 278.0)
        scrollDirection = .vertical
        minimumLineSpacing = 100.0
        sectionInset = UIEdgeInsetsMake(100.0, 60.0, 100, 60.0)
    }
}
```

Any doubts just let me know. Thanks.
