### ISSUE TITLE
how to customise design ?

### ISSUE THREAD

**Issue by gchoudhary26** [PPacie/SwipingCarousel#2]
I want to customise the design little bit, like show 6 cells on screen and then have all the animations in it.
Is there any way for changing the spacing between the cells ?

**Comment by PPacie** [comment]
Hi,

You can show the number of cells you need. You do that when setting your `collectionView dataSource`. 

For changing the space between the cells you need to set the following `UICollectionViewDelegateFlowLayout` delegate method.

For example: 

```
extension MyViewController: UICollectionViewDelegateFlowLayout {
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        return 10.0
    }   
}

```    

Hope it helps, any doubts just let me know =)

**Comment by gchoudhary26** [comment]
hi PPacie,

Thanks for help, but its not working for me as i have to show 5 items on screen.
Now i can only see 3 items on screen, i want to have 5 items on screen.


Thanks!

**Comment by PPacie** [comment]
Ohh now I got what you mean by number of items on screen.

Ok, to get something similar to the UI you are required you will need to modify the layoutAttributes of the FlowLayout. It wasn't supported before. 

Today I've made the activeDistance property public so you have now access to that property. The default value is 200.

To completely modify the UI you will have to set the SwipingCarouselFlowLayout programmatically. Something like this:

```
 @IBOutlet weak var collectionView: UICollectionView! { didSet {
        collectionView.register(CardCollectionViewCell.nib, forCellWithReuseIdentifier: CardCollectionViewCell.reuseIdentifier)
        
        let layout = SwipingCarouselFlowLayout()
        layout.activeDistance = 50 // your desired value. Remember 200 is the default.
        collectionView.setCollectionViewLayout(layout, animated: false)
        }
    }

```

Lastly, you will have to play with the `UICollectionViewDelegateFlowLayout` delegate methods.

For example:

```
extension MyViewController: UICollectionViewDelegateFlowLayout {
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAt section: Int) -> UIEdgeInsets {
        return UIEdgeInsets(top: 200, left: 120, bottom: 200, right: 120)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: 150.0, height: 230.0)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        return -80.0
    }
} 
```

![simulator screen shot may 29 2017 11 53 14](https://cloud.githubusercontent.com/assets/4922383/26554228/78a1964e-4465-11e7-9fb0-90ffefd5e831.png)


Remember to run carthage update to get the latest release version 1.3.

**Comment by gchoudhary26** [comment]
Hi PPacie, 

Thanks for your help, you made my day 👍 
I will look into it.

Thanks!
