### ISSUE TITLE
How can i use this method?  override public func targetContentOffset(forProposedContentOffset proposedContentOffset: CGPoint, withScrollingVelocity velocity: CGPoint) -> CGPoint

### ISSUE THREAD

**Issue by adnanatflo** [PPacie/SwipingCarousel#4]
override public func targetContentOffset(forProposedContentOffset proposedContentOffset: CGPoint, withScrollingVelocity velocity: CGPoint) -> CGPoint

**Comment by PPacie** [comment]
Hi,

In this case you can't. I guess the best option is to fork the project and modify the layout as you will =)

Cheers,
Pablo.
