### ISSUE TITLE
SwipingCarousel doesnt work with Swift 3.2/4.0

### ISSUE THREAD

**Issue by suranavarun** [PPacie/SwipingCarousel#5]
We have recently migrated to XCode 9 which uses Swift 3.2 or 4.0. Now when i try to run the app it says module complied with Swift 3.1 cannot be imported in Swift 3.2.2.

**Comment by PPacie** [comment]
Hi @suranavarun 
1 ) You should select the version of Xcode that you require to compile the framework with. You do it from `Xcode preferences -> Locations and check/change the command line tools to Xcode X`
2) in terminal: `carthage update SwipingCarousel --platform iOS`

Sorry for the delay in the response. Please try that and let me know if you still have issues. 

Thanks.
