### ISSUE TITLE
Left & Right Swipes don't always register

### ISSUE THREAD

**Issue by cdeck95** [PPacie/SwipingCarousel#6]
About 60% of the time, my swipes to the left or right do not register. However, once I get it to swipe, it is reactive until another card gets in focus.

**Comment by cdeck95** [comment]
Seems very sensitive to the finger not moving directly left or right, if I go slightly up or down as I swipe over, it thinks I am swiping up or down. Anyway to alter the sensitivity to find a median?

I see the methods in the source code for determining whether we are swiping up, down, left, or right. It does a check on whether the movement in the Y direction is greater than the constant value. Anyway to change the constant to be higher? Can we override that?

**Comment by cdeck95** [comment]
For anyone else using this repo, just implement the 4 files inside your own project instead of using carthage to import. Then change the code in afterSwipeAction() in the SwpingCarouselCellManager class to look like below:

This check is to keep the action only on the focus card. If you started the swipe from outside the current cards frame, it re-centered the already focused card, leaving you with no scroll. The way I have it below is more reactive for a swipe heavy interface.

```
 func afterSwipeAction() {
            if swipeDistanceOnY > Constants.SwipeDistanceToTakeAction {
                downAction()
            } else if swipeDistanceOnY < -Constants.SwipeDistanceToTakeAction {
                upAction()
            } else {
                UIView.animate(withDuration: Constants.CenterImageAnimationDuration, animations: {
                    self.cell?.center = self.originalPoint
                })
            }
}
```

**Comment by cdeck95** [comment]
I should also mention, I implemented the override methods for the layout (seen below). So it shows more than one card at a time in my view controller - which is why this even happened in the first place.

```
let layout = SwipingCarouselFlowLayout()
layout.activeDistance = 50
collectionView.setCollectionViewLayout(layout, animated: false)
```

**Comment by PPacie** [comment]
Hi Christopher, 

Sorry for not answering on time.

Thanks for going forward and fix the swipe by yourself. I will try to incorporate those updates in the next version.

Cheers.
